version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGITAWSStage02Project
  gitServerName: kusi_AWSStage02
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqagitawsstage02.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQAGITAWSStage02Project
    version: "1.0"
- serviceName: project.siqagitawsstage02.integrations:AlertsCRTandERT
  packages:
  - name: SIQAGITAWSStage02Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: project.siqagitawsstage02.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAGITAWSStage02Project
    version: "1.0"
- serviceName: project.siqagitawsstage02.integrations:deepclonetest
  packages:
  - name: SIQAGITAWSStage02Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
